printWidth: 90
tabWidth: 4
overrides:
    - files: "*.{json,yml,yaml}"
      options:
          tabWidth: 4
    - files: "cumulusci.yml"
      options:
          tabWidth: 4
    - files: "**/lwc/**/*.html"
      options:
          parser: lwc
    - files: "**/lwc/**/*.js"
      options:
          trailingComma: "es5"
    - files: "**/aura/**/*.{cmp,page,component,xml}"
      options:
          parser: "html"
    - files: "**/aura/**/*.js"
      options:
          trailingComma: "none"
    - files: "*.cls"
      options:
          plugins: ["prettier-plugin-apex"]
          parser: apex
          apexInsertFinalNewline: true
    - files: "*.apex"
      options:
          plugins: ["prettier-plugin-apex"]
          parser: apex-anonymous
          apexInsertFinalNewline: true
