BEGIN TRANSACTION;
CREATE TABLE contacts (
	id INTEGER NOT NULL, 
	"npe01__SystemAccountProcessor__c" VARCHAR(255), 
	"npe01__AlternateEmail__c" VARCHAR(255), 
	"npe01__HomeEmail__c" VARCHAR(255), 
	"npe01__Preferred_Email__c" VARCHAR(255), 
	"npe01__PreferredPhone__c" VARCHAR(255), 
	"npe01__Pråimary_Address_Type__c" VARCHAR(255), 
	"npe01__Private__c" VARCHAR(255), 
	"npe01__Secondary_Address_Type__c" VARCHAR(255), 
	"npe01__WorkEmail__c" VARCHAR(255), 
	"npe01__WorkPhone__c" VARCHAR(255), 
	PRIMARY KEY (id)
);
INSERT INTO "contacts" VALUES(1,'','','daliaosborn@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(2,'','','laurawoodard@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(3,'','','simondavila@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(4,'','','jamarcusbarnett@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(5,'','','adriannanorman@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(6,'','','donnasnow@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(7,'','','garywood@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(8,'','','reagannorton@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(9,'','','jaylinmorgan@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(10,'','','miradecker@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(11,'','','mayalambert@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(12,'','','finleybarry@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(13,'','','shanegibson@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(14,'','','benoneill@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(15,'','','maiacooley@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(16,'','','oliveleach@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(17,'','','oswaldopacheco@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(18,'','','nicorivers@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(19,'','','tiaragriffith@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(20,'','','declanglenn@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(21,'','','madalynfrancis@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(22,'','','mathewrhodes@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(23,'','','jessicawoods@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(24,'','','aliaduarte@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(25,'','','eliwhite@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(26,'','','tatianalang@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(27,'','','giaramirez@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(28,'','','alejandroserrano@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(29,'','','myagalloway@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(30,'','','adamclark@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(31,'','','marisolgonzales@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(32,'','','myacobb@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(33,'','','jayshah@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(34,'','','nancyarroyo@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(35,'','','neilhuerta@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(36,'','','aubriebooker@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(37,'','','emeliamercer@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(38,'','','yadielhorton@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(39,'','','taniyahrios@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(40,'','','peytoncraig@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(41,'','','francescaoliver@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(42,'','','albertmontgomery@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(43,'','','meredithcooke@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(44,'','','mckaylamorrison@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(45,'','','hayleybright@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(46,'','','laurahernandez@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(47,'','','dayanaatkins@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(48,'','','khloestanley@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(49,'','','rayfischer@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(50,'','','caseykline@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(51,'','','aronjoyce@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(52,'','','diegocase@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(53,'','','chelseagraves@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(54,'','','ruthwu@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(55,'','','isaacgrant@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(56,'','','audrinarojas@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(57,'','','makhivillegas@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(58,'','','koenchase@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(59,'','','hailieholder@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(60,'','','cayleepollard@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(61,'','','guillermoquinn@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(62,'','','dominikwilkinson@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(63,'','','simonekeller@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(64,'','','violetellis@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(65,'','','samirneal@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(66,'','','miramcconnell@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(67,'','','aniyaarellano@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(68,'','','rafaelvelasquez@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(69,'','','jakaylaglover@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(70,'','','angelolutz@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(71,'','','audrinagraves@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(72,'','','turnercarson@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(73,'','','emeliafletcher@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(74,'','','mackenziehernandez@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(75,'','','ryanhardin@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(76,'','','miraolson@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(77,'','','annaorr@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(78,'','','tyronepearson@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(79,'','','naimacrawford@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(80,'','','joesalinas@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(81,'','','maleahbullock@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(82,'','','anikasolomon@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(83,'','','thiggins@example.com','Personal','Home','Home','false','','','');
INSERT INTO "contacts" VALUES(84,'','','lhiggins@example.com','Personal','Home','Home','false','','','');
INSERT INTO "contacts" VALUES(85,'','','jeremyadams@example.com','Personal','Home','Home','false','','','');
INSERT INTO "contacts" VALUES(86,'','','angelaadams@example.com','Personal','Home','Home','false','','','');
INSERT INTO "contacts" VALUES(87,'','','','Personal','Home','Home','false','','','');
INSERT INTO "contacts" VALUES(88,'','','alanbaker@example.com','Personal','Home','Home','false','','','');
INSERT INTO "contacts" VALUES(89,'','','robinbanks@example.com','Personal','Home','Home','false','','','');
INSERT INTO "contacts" VALUES(90,'','','darrylgraham@example.com','Personal','Home','Home','false','','','');
INSERT INTO "contacts" VALUES(91,'','','lynnbarnes@example.com','Personal','Home','Home','false','','','');
INSERT INTO "contacts" VALUES(92,'','','davidbarnes@example.com','Personal','Home','Home','false','','','');
INSERT INTO "contacts" VALUES(93,'','','jasonbarnes@example.com','Personal','Home','Home','false','','','');
INSERT INTO "contacts" VALUES(94,'','','anneboyd@example.com','Personal','Home','Home','false','','','');
INSERT INTO "contacts" VALUES(95,'','','ariellabranch@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(96,'','','normaburke@example.com','Personal','Home','Home','false','','','');
INSERT INTO "contacts" VALUES(97,'','','bobbyhenderson@example.com','Personal','Home','Home','false','','','');
INSERT INTO "contacts" VALUES(98,'','','anthonyhill@example.com','Personal','Home','Home','false','','','');
INSERT INTO "contacts" VALUES(99,'','','virginiaholmes@example.com','Personal','Home','Home','false','','','');
INSERT INTO "contacts" VALUES(100,'','','josejenkins@example.com','Personal','Home','Home','false','','','');
INSERT INTO "contacts" VALUES(101,'','','craigjohnso@example.com','Personal','Home','Home','false','','','');
INSERT INTO "contacts" VALUES(102,'','','','Personal','Home','Home','false','','','');
INSERT INTO "contacts" VALUES(103,'','','barbarajohnson@example.com','Personal','Home','Home','false','','','');
INSERT INTO "contacts" VALUES(104,'','','joseburgess@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(105,'','','brendabass@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(106,'','','nikhilbishop@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(107,'','','juliettecisneros@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(108,'','','jaydonbates@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(109,'','','alanaowen@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(110,'','','cruzkerr@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(111,'','','beaueaton@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(112,'','','chancerasmussen@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(113,'','','jamesrichards@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(114,'','','khloecampos@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(115,'','','ameliebond@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(116,'','','juliemyers@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(117,'','','jaydastanton@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(118,'','','heidiwoods@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(119,'','','javonrodgers@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(120,'','','leiaspence@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(121,'','','leonclayton@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(122,'','','marcrichard@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(123,'','','jordanwaller@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(124,'','','jacehampton@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(125,'','','silasneal@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(126,'','','soniagentry@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(127,'','','alisonbarr@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(128,'','','vupham@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(129,'','','kellencooley@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(130,'','','josiemcclure@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(131,'','','jayzimmerman@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(132,'','','melaniewheeler@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(133,'','','fernandobeltran@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(134,'','','yulianabird@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(135,'','','alysonduffy@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(136,'','','nylawoods@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(137,'','','aaronvaldez@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(138,'','','johnmills@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(139,'','','shannongreene@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(140,'','','marcoescobar@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(141,'','','marcushuynh@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(142,'','','lorelaigross@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(143,'','','elsaguerrero@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(144,'','','yeseniaritter@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(145,'','','abrahamsims@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(146,'','','kylehuffman@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(147,'','','corahall@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(148,'','','isaacbarker@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(149,'','','kaileyglass@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(150,'','','delilahibarra@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(151,'','','zackerymorgan@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(152,'','','ayannagonzalez@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(153,'','','duncanbowers@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(154,'','','laurynodom@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(155,'','','yusefflores@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(156,'','','semajwall@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(157,'','','frankiewaller@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(158,'','','eliezerbray@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(159,'','','jadenconner@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(160,'','','stevenharper@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(161,'','','karissaaguilar@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(162,'','','tiaracummings@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(163,'','','taniyasingleton@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(164,'','','ceciliacardenas@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(165,'','','christinawebster@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(166,'','','emiliecosta@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(167,'','','ayanahumphrey@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(168,'','','luciacain@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(169,'','','amayadunlap@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(170,'','','derrickblackwell@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(171,'','','aliceirwin@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(172,'','','fabianhughes@example.com','Personal','Home','','false','','','');
INSERT INTO "contacts" VALUES(173,'','','raelynnwells@example.com','Personal','Home','','false','','','');
CREATE TABLE household_accounts (
	id INTEGER NOT NULL, 
	"npe01__SYSTEM_AccountType__c" VARCHAR(255), 
	"npe01__SYSTEMIsIndividual__c" VARCHAR(255), 
	PRIMARY KEY (id)
);
INSERT INTO "household_accounts" VALUES(1,'Household Account','true');
INSERT INTO "household_accounts" VALUES(2,'Household Account','true');
INSERT INTO "household_accounts" VALUES(3,'Household Account','true');
INSERT INTO "household_accounts" VALUES(4,'Household Account','true');
INSERT INTO "household_accounts" VALUES(5,'Household Account','true');
INSERT INTO "household_accounts" VALUES(6,'Household Account','true');
INSERT INTO "household_accounts" VALUES(7,'Household Account','true');
INSERT INTO "household_accounts" VALUES(8,'Household Account','true');
INSERT INTO "household_accounts" VALUES(9,'Household Account','true');
INSERT INTO "household_accounts" VALUES(10,'Household Account','true');
INSERT INTO "household_accounts" VALUES(11,'Household Account','true');
INSERT INTO "household_accounts" VALUES(12,'Household Account','true');
INSERT INTO "household_accounts" VALUES(13,'Household Account','true');
INSERT INTO "household_accounts" VALUES(14,'Household Account','true');
INSERT INTO "household_accounts" VALUES(15,'Household Account','true');
INSERT INTO "household_accounts" VALUES(16,'Household Account','true');
INSERT INTO "household_accounts" VALUES(17,'Household Account','true');
INSERT INTO "household_accounts" VALUES(18,'Household Account','true');
INSERT INTO "household_accounts" VALUES(19,'Household Account','true');
INSERT INTO "household_accounts" VALUES(20,'Household Account','true');
INSERT INTO "household_accounts" VALUES(21,'Household Account','true');
INSERT INTO "household_accounts" VALUES(22,'Household Account','true');
INSERT INTO "household_accounts" VALUES(23,'Household Account','true');
INSERT INTO "household_accounts" VALUES(24,'Household Account','true');
INSERT INTO "household_accounts" VALUES(25,'Household Account','true');
INSERT INTO "household_accounts" VALUES(26,'Household Account','true');
INSERT INTO "household_accounts" VALUES(27,'Household Account','true');
INSERT INTO "household_accounts" VALUES(28,'Household Account','true');
INSERT INTO "household_accounts" VALUES(29,'Household Account','true');
INSERT INTO "household_accounts" VALUES(30,'Household Account','true');
INSERT INTO "household_accounts" VALUES(31,'Household Account','true');
INSERT INTO "household_accounts" VALUES(32,'Household Account','true');
INSERT INTO "household_accounts" VALUES(33,'Household Account','true');
INSERT INTO "household_accounts" VALUES(34,'Household Account','true');
INSERT INTO "household_accounts" VALUES(35,'Household Account','true');
INSERT INTO "household_accounts" VALUES(36,'Household Account','true');
INSERT INTO "household_accounts" VALUES(37,'Household Account','true');
INSERT INTO "household_accounts" VALUES(38,'Household Account','true');
INSERT INTO "household_accounts" VALUES(39,'Household Account','true');
INSERT INTO "household_accounts" VALUES(40,'Household Account','true');
INSERT INTO "household_accounts" VALUES(41,'Household Account','true');
INSERT INTO "household_accounts" VALUES(42,'Household Account','true');
INSERT INTO "household_accounts" VALUES(43,'Household Account','true');
INSERT INTO "household_accounts" VALUES(44,'Household Account','true');
INSERT INTO "household_accounts" VALUES(45,'Household Account','true');
INSERT INTO "household_accounts" VALUES(46,'Household Account','true');
INSERT INTO "household_accounts" VALUES(47,'Household Account','true');
INSERT INTO "household_accounts" VALUES(48,'Household Account','true');
INSERT INTO "household_accounts" VALUES(49,'Household Account','true');
INSERT INTO "household_accounts" VALUES(50,'Household Account','true');
INSERT INTO "household_accounts" VALUES(51,'Household Account','true');
INSERT INTO "household_accounts" VALUES(52,'Household Account','true');
INSERT INTO "household_accounts" VALUES(53,'Household Account','true');
INSERT INTO "household_accounts" VALUES(54,'Household Account','true');
INSERT INTO "household_accounts" VALUES(55,'Household Account','true');
INSERT INTO "household_accounts" VALUES(56,'Household Account','true');
INSERT INTO "household_accounts" VALUES(57,'Household Account','true');
INSERT INTO "household_accounts" VALUES(58,'Household Account','true');
INSERT INTO "household_accounts" VALUES(59,'Household Account','true');
INSERT INTO "household_accounts" VALUES(60,'Household Account','true');
INSERT INTO "household_accounts" VALUES(61,'Household Account','true');
INSERT INTO "household_accounts" VALUES(62,'Household Account','true');
INSERT INTO "household_accounts" VALUES(63,'Household Account','true');
INSERT INTO "household_accounts" VALUES(64,'Household Account','true');
INSERT INTO "household_accounts" VALUES(65,'Household Account','true');
INSERT INTO "household_accounts" VALUES(66,'Household Account','true');
INSERT INTO "household_accounts" VALUES(67,'Household Account','true');
INSERT INTO "household_accounts" VALUES(68,'Household Account','true');
INSERT INTO "household_accounts" VALUES(69,'Household Account','true');
INSERT INTO "household_accounts" VALUES(70,'Household Account','true');
INSERT INTO "household_accounts" VALUES(71,'Household Account','true');
INSERT INTO "household_accounts" VALUES(72,'Household Account','true');
INSERT INTO "household_accounts" VALUES(73,'Household Account','true');
INSERT INTO "household_accounts" VALUES(74,'Household Account','true');
INSERT INTO "household_accounts" VALUES(75,'Household Account','true');
INSERT INTO "household_accounts" VALUES(76,'Household Account','true');
INSERT INTO "household_accounts" VALUES(77,'Household Account','true');
INSERT INTO "household_accounts" VALUES(78,'Household Account','true');
INSERT INTO "household_accounts" VALUES(79,'Household Account','true');
INSERT INTO "household_accounts" VALUES(80,'Household Account','true');
INSERT INTO "household_accounts" VALUES(81,'Household Account','true');
INSERT INTO "household_accounts" VALUES(82,'Household Account','true');
INSERT INTO "household_accounts" VALUES(83,'Household Account','true');
INSERT INTO "household_accounts" VALUES(84,'Household Account','true');
INSERT INTO "household_accounts" VALUES(85,'Household Account','true');
INSERT INTO "household_accounts" VALUES(86,'Household Account','true');
INSERT INTO "household_accounts" VALUES(87,'Household Account','true');
INSERT INTO "household_accounts" VALUES(88,'Household Account','true');
INSERT INTO "household_accounts" VALUES(89,'Household Account','true');
INSERT INTO "household_accounts" VALUES(90,'Household Account','true');
INSERT INTO "household_accounts" VALUES(91,'Household Account','true');
INSERT INTO "household_accounts" VALUES(92,'Household Account','true');
INSERT INTO "household_accounts" VALUES(93,'Household Account','true');
INSERT INTO "household_accounts" VALUES(94,'Household Account','true');
INSERT INTO "household_accounts" VALUES(95,'Household Account','true');
INSERT INTO "household_accounts" VALUES(96,'Household Account','true');
INSERT INTO "household_accounts" VALUES(97,'Household Account','true');
INSERT INTO "household_accounts" VALUES(98,'Household Account','true');
INSERT INTO "household_accounts" VALUES(99,'Household Account','true');
INSERT INTO "household_accounts" VALUES(100,'Household Account','true');
INSERT INTO "household_accounts" VALUES(101,'Household Account','true');
INSERT INTO "household_accounts" VALUES(102,'Household Account','true');
INSERT INTO "household_accounts" VALUES(103,'Household Account','true');
INSERT INTO "household_accounts" VALUES(104,'Household Account','true');
INSERT INTO "household_accounts" VALUES(105,'Household Account','true');
INSERT INTO "household_accounts" VALUES(106,'Household Account','true');
INSERT INTO "household_accounts" VALUES(107,'Household Account','true');
INSERT INTO "household_accounts" VALUES(108,'Household Account','true');
INSERT INTO "household_accounts" VALUES(109,'Household Account','true');
INSERT INTO "household_accounts" VALUES(110,'Household Account','true');
INSERT INTO "household_accounts" VALUES(111,'Household Account','true');
INSERT INTO "household_accounts" VALUES(112,'Household Account','true');
INSERT INTO "household_accounts" VALUES(113,'Household Account','true');
INSERT INTO "household_accounts" VALUES(114,'Household Account','true');
INSERT INTO "household_accounts" VALUES(115,'Household Account','true');
INSERT INTO "household_accounts" VALUES(116,'Household Account','true');
INSERT INTO "household_accounts" VALUES(117,'Household Account','true');
INSERT INTO "household_accounts" VALUES(118,'Household Account','true');
INSERT INTO "household_accounts" VALUES(119,'Household Account','true');
INSERT INTO "household_accounts" VALUES(120,'Household Account','true');
INSERT INTO "household_accounts" VALUES(121,'Household Account','true');
INSERT INTO "household_accounts" VALUES(122,'Household Account','true');
INSERT INTO "household_accounts" VALUES(123,'Household Account','true');
INSERT INTO "household_accounts" VALUES(124,'Household Account','true');
INSERT INTO "household_accounts" VALUES(125,'Household Account','true');
INSERT INTO "household_accounts" VALUES(126,'Household Account','true');
INSERT INTO "household_accounts" VALUES(127,'Household Account','true');
INSERT INTO "household_accounts" VALUES(128,'Household Account','true');
INSERT INTO "household_accounts" VALUES(129,'Household Account','true');
INSERT INTO "household_accounts" VALUES(130,'Household Account','true');
INSERT INTO "household_accounts" VALUES(131,'Household Account','true');
INSERT INTO "household_accounts" VALUES(132,'Household Account','true');
INSERT INTO "household_accounts" VALUES(133,'Household Account','true');
INSERT INTO "household_accounts" VALUES(134,'Household Account','true');
INSERT INTO "household_accounts" VALUES(135,'Household Account','true');
INSERT INTO "household_accounts" VALUES(136,'Household Account','true');
INSERT INTO "household_accounts" VALUES(137,'Household Account','true');
INSERT INTO "household_accounts" VALUES(138,'Household Account','true');
INSERT INTO "household_accounts" VALUES(139,'Household Account','true');
INSERT INTO "household_accounts" VALUES(140,'Household Account','true');
INSERT INTO "household_accounts" VALUES(141,'Household Account','true');
INSERT INTO "household_accounts" VALUES(142,'Household Account','true');
INSERT INTO "household_accounts" VALUES(143,'Household Account','true');
INSERT INTO "household_accounts" VALUES(144,'Household Account','true');
INSERT INTO "household_accounts" VALUES(145,'Household Account','true');
INSERT INTO "household_accounts" VALUES(146,'Household Account','true');
INSERT INTO "household_accounts" VALUES(147,'Household Account','true');
INSERT INTO "household_accounts" VALUES(148,'Household Account','true');
INSERT INTO "household_accounts" VALUES(149,'Household Account','true');
INSERT INTO "household_accounts" VALUES(150,'Household Account','true');
INSERT INTO "household_accounts" VALUES(151,'Household Account','true');
INSERT INTO "household_accounts" VALUES(152,'Household Account','true');
INSERT INTO "household_accounts" VALUES(153,'Household Account','true');
INSERT INTO "household_accounts" VALUES(154,'Household Account','true');
INSERT INTO "household_accounts" VALUES(155,'Household Account','true');
INSERT INTO "household_accounts" VALUES(156,'Household Account','true');
INSERT INTO "household_accounts" VALUES(157,'Household Account','true');
INSERT INTO "household_accounts" VALUES(158,'Household Account','true');
INSERT INTO "household_accounts" VALUES(159,'Household Account','true');
INSERT INTO "household_accounts" VALUES(160,'Household Account','true');
INSERT INTO "household_accounts" VALUES(161,'Household Account','true');
INSERT INTO "household_accounts" VALUES(162,'Household Account','true');
INSERT INTO "household_accounts" VALUES(163,'Household Account','true');
INSERT INTO "household_accounts" VALUES(164,'Household Account','true');
INSERT INTO "household_accounts" VALUES(165,'Household Account','true');
INSERT INTO "household_accounts" VALUES(166,'','false');
INSERT INTO "household_accounts" VALUES(167,'','false');
INSERT INTO "household_accounts" VALUES(168,'','false');
INSERT INTO "household_accounts" VALUES(169,'','false');
CREATE TABLE npsp__donations (
	id INTEGER NOT NULL, 
	"npe01__Membership_Origin__c" VARCHAR(255), 
	"npe01__Member_Level__c" VARCHAR(255), 
	"npe01__Membership_Start_Date__c" VARCHAR(255), 
	"npe01__Membership_End_Date__c" VARCHAR(255), 
	"npe01__Do_Not_Automatically_Create_Payment__c" VARCHAR(255), 
	PRIMARY KEY (id)
);
INSERT INTO "npsp__donations" VALUES(1,'','','','','false');
INSERT INTO "npsp__donations" VALUES(2,'','','','','false');
INSERT INTO "npsp__donations" VALUES(3,'','','','','false');
CREATE TABLE organization_accounts (
	id INTEGER NOT NULL, 
	"npe01__SYSTEM_AccountType__c" VARCHAR(255), 
	"npe01__SYSTEMIsIndividual__c" VARCHAR(255), 
	PRIMARY KEY (id)
);
INSERT INTO "organization_accounts" VALUES(1,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(2,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(3,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(4,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(5,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(6,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(7,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(8,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(9,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(10,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(11,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(12,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(13,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(14,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(15,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(16,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(17,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(18,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(19,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(20,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(21,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(22,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(23,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(24,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(25,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(26,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(27,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(28,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(29,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(30,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(31,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(32,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(33,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(34,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(35,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(36,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(37,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(38,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(39,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(40,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(41,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(42,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(43,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(44,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(45,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(46,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(47,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(48,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(49,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(50,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(51,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(52,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(53,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(54,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(55,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(56,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(57,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(58,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(59,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(60,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(61,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(62,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(63,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(64,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(65,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(66,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(67,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(68,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(69,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(70,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(71,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(72,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(73,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(74,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(75,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(76,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(77,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(78,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(79,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(80,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(81,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(82,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(83,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(84,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(85,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(86,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(87,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(88,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(89,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(90,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(91,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(92,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(93,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(94,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(95,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(96,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(97,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(98,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(99,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(100,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(101,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(102,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(103,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(104,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(105,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(106,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(107,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(108,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(109,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(110,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(111,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(112,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(113,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(114,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(115,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(116,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(117,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(118,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(119,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(120,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(121,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(122,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(123,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(124,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(125,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(126,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(127,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(128,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(129,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(130,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(131,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(132,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(133,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(134,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(135,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(136,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(137,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(138,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(139,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(140,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(141,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(142,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(143,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(144,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(145,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(146,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(147,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(148,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(149,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(150,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(151,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(152,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(153,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(154,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(155,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(156,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(157,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(158,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(159,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(160,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(161,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(162,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(163,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(164,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(165,'Household Account','true');
INSERT INTO "organization_accounts" VALUES(166,'','false');
INSERT INTO "organization_accounts" VALUES(167,'','false');
INSERT INTO "organization_accounts" VALUES(168,'','false');
INSERT INTO "organization_accounts" VALUES(169,'','false');
COMMIT;
