BEGIN TRANSACTION;
CREATE TABLE "Account__HH_Account" (
	id INTEGER NOT NULL, 
	"Name" VARCHAR(255), 
	"npe01__SYSTEM_AccountType__c" VARCHAR(255), 
	"npe01__SYSTEMIsIndividual__c" VARCHAR(255), 
	PRIMARY KEY (id)
);
INSERT INTO "Account__HH_Account" VALUES(1,'Osborn Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(2,'Pearson Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(3,'Branch Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(4,'Bates Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(5,'Rodgers Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(6,'Mcclure Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(7,'Huynh Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(8,'Gonzalez Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(9,'Singleton Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(10,'Woodard Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(11,'Gibson Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(12,'Duarte Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(13,'Huerta Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(14,'Hernandez Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(15,'Villegas Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(16,'Velasquez Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(17,'Hardin Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(18,'Olson Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(19,'Orr Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(20,'Salinas Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(21,'Bullock Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(22,'Solomon Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(23,'Higgins Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(24,'Adams Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(25,'Baker Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(26,'Banks and Graham Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(27,'Barnes Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(28,'Boyd Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(29,'Burke Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(30,'Henderson Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(31,'Hill Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(32,'Holmes Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(33,'Jenkins Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(34,'Johnson Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(35,'Burgess Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(36,'Bass Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(37,'Bishop Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(38,'Cisneros Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(39,'Owen Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(40,'Kerr Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(41,'Crawford Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(42,'Eaton Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(43,'Rasmussen Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(44,'Campos Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(45,'Bond Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(46,'Myers Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(47,'Stanton Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(48,'Woods Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(49,'Spence Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(50,'Clayton Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(51,'Richard Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(52,'Waller Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(53,'Hampton Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(54,'Neal Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(55,'Gentry Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(56,'Barr Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(57,'Pham Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(58,'Cooley Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(59,'Zimmerman Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(60,'Wheeler Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(61,'Beltran Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(62,'Bird Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(63,'Duffy Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(64,'Woods Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(65,'Richards Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(66,'Valdez Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(67,'Mills Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(68,'Greene Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(69,'Escobar Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(70,'Gross Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(71,'Guerrero Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(72,'Ritter Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(73,'Sims Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(74,'Huffman Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(75,'Hall Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(76,'Barker Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(77,'Glass Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(78,'Ibarra Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(79,'Morgan Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(80,'Bowers Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(81,'Odom Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(82,'Flores Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(83,'Wall Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(84,'Waller Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(85,'Bray Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(86,'Conner Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(87,'Harper Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(88,'Aguilar Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(89,'Cummings Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(90,'Cardenas Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(91,'Webster Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(92,'Costa Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(93,'Humphrey Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(94,'Cain Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(95,'Dunlap Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(96,'Blackwell Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(97,'Irwin Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(98,'Hughes Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(99,'Wells Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(100,'Davila Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(101,'Barnett Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(102,'Norman Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(103,'Snow Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(104,'Wood Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(105,'Norton Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(106,'Morgan Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(107,'Decker Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(108,'Lambert Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(109,'Barry Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(110,'Oneill Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(111,'Cooley Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(112,'Leach Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(113,'Pacheco Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(114,'Rivers Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(115,'Griffith Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(116,'Glenn Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(117,'Francis Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(118,'Rhodes Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(119,'White Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(120,'Lang Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(121,'Ramirez Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(122,'Serrano Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(123,'Galloway Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(124,'Clark Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(125,'Gonzales Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(126,'Cobb Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(127,'Shah Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(128,'Arroyo Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(129,'Booker Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(130,'Mercer Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(131,'Horton Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(132,'Rios Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(133,'Craig Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(134,'Oliver Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(135,'Montgomery Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(136,'Cooke Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(137,'Morrison Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(138,'Bright Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(139,'Atkins Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(140,'Woods Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(141,'Stanley Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(142,'Fischer Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(143,'Kline Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(144,'Joyce Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(145,'Case Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(146,'Graves Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(147,'Wu Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(148,'Grant Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(149,'Rojas Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(150,'Chase Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(151,'Holder Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(152,'Pollard Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(153,'Quinn Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(154,'Wilkinson Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(155,'Keller Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(156,'Ellis Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(157,'Neal Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(158,'Mcconnell Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(159,'Arellano Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(160,'Glover Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(161,'Lutz Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(162,'Graves Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(163,'Carson Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(164,'Fletcher Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(165,'Hernandez Household','Household Account','true');
INSERT INTO "Account__HH_Account" VALUES(166,'Marble Foundation','','false');
INSERT INTO "Account__HH_Account" VALUES(167,'Future Potential Fund','','false');
INSERT INTO "Account__HH_Account" VALUES(168,'City Department of Human Services','','false');
INSERT INTO "Account__HH_Account" VALUES(169,'127th Street Community Center','','false');
CREATE TABLE "Account__Organization" (
	id INTEGER NOT NULL, 
	"Name" VARCHAR(255), 
	"npe01__SYSTEM_AccountType__c" VARCHAR(255), 
	"npe01__SYSTEMIsIndividual__c" VARCHAR(255), 
	PRIMARY KEY (id)
);
INSERT INTO "Account__Organization" VALUES(1,'Osborn Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(2,'Pearson Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(3,'Branch Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(4,'Bates Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(5,'Rodgers Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(6,'Mcclure Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(7,'Huynh Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(8,'Gonzalez Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(9,'Singleton Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(10,'Woodard Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(11,'Gibson Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(12,'Duarte Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(13,'Huerta Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(14,'Hernandez Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(15,'Villegas Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(16,'Velasquez Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(17,'Hardin Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(18,'Olson Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(19,'Orr Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(20,'Salinas Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(21,'Bullock Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(22,'Solomon Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(23,'Higgins Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(24,'Adams Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(25,'Baker Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(26,'Banks and Graham Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(27,'Barnes Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(28,'Boyd Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(29,'Burke Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(30,'Henderson Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(31,'Hill Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(32,'Holmes Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(33,'Jenkins Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(34,'Johnson Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(35,'Burgess Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(36,'Bass Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(37,'Bishop Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(38,'Cisneros Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(39,'Owen Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(40,'Kerr Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(41,'Crawford Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(42,'Eaton Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(43,'Rasmussen Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(44,'Campos Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(45,'Bond Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(46,'Myers Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(47,'Stanton Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(48,'Woods Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(49,'Spence Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(50,'Clayton Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(51,'Richard Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(52,'Waller Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(53,'Hampton Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(54,'Neal Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(55,'Gentry Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(56,'Barr Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(57,'Pham Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(58,'Cooley Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(59,'Zimmerman Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(60,'Wheeler Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(61,'Beltran Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(62,'Bird Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(63,'Duffy Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(64,'Woods Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(65,'Richards Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(66,'Valdez Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(67,'Mills Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(68,'Greene Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(69,'Escobar Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(70,'Gross Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(71,'Guerrero Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(72,'Ritter Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(73,'Sims Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(74,'Huffman Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(75,'Hall Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(76,'Barker Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(77,'Glass Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(78,'Ibarra Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(79,'Morgan Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(80,'Bowers Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(81,'Odom Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(82,'Flores Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(83,'Wall Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(84,'Waller Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(85,'Bray Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(86,'Conner Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(87,'Harper Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(88,'Aguilar Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(89,'Cummings Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(90,'Cardenas Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(91,'Webster Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(92,'Costa Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(93,'Humphrey Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(94,'Cain Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(95,'Dunlap Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(96,'Blackwell Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(97,'Irwin Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(98,'Hughes Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(99,'Wells Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(100,'Davila Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(101,'Barnett Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(102,'Norman Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(103,'Snow Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(104,'Wood Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(105,'Norton Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(106,'Morgan Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(107,'Decker Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(108,'Lambert Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(109,'Barry Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(110,'Oneill Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(111,'Cooley Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(112,'Leach Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(113,'Pacheco Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(114,'Rivers Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(115,'Griffith Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(116,'Glenn Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(117,'Francis Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(118,'Rhodes Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(119,'White Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(120,'Lang Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(121,'Ramirez Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(122,'Serrano Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(123,'Galloway Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(124,'Clark Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(125,'Gonzales Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(126,'Cobb Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(127,'Shah Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(128,'Arroyo Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(129,'Booker Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(130,'Mercer Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(131,'Horton Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(132,'Rios Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(133,'Craig Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(134,'Oliver Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(135,'Montgomery Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(136,'Cooke Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(137,'Morrison Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(138,'Bright Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(139,'Atkins Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(140,'Woods Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(141,'Stanley Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(142,'Fischer Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(143,'Kline Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(144,'Joyce Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(145,'Case Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(146,'Graves Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(147,'Wu Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(148,'Grant Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(149,'Rojas Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(150,'Chase Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(151,'Holder Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(152,'Pollard Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(153,'Quinn Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(154,'Wilkinson Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(155,'Keller Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(156,'Ellis Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(157,'Neal Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(158,'Mcconnell Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(159,'Arellano Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(160,'Glover Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(161,'Lutz Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(162,'Graves Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(163,'Carson Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(164,'Fletcher Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(165,'Hernandez Household','Household Account','true');
INSERT INTO "Account__Organization" VALUES(166,'Marble Foundation','','false');
INSERT INTO "Account__Organization" VALUES(167,'Future Potential Fund','','false');
INSERT INTO "Account__Organization" VALUES(168,'City Department of Human Services','','false');
INSERT INTO "Account__Organization" VALUES(169,'127th Street Community Center','','false');
CREATE TABLE "Contact" (
	id INTEGER NOT NULL, 
	"FirstName" VARCHAR(255), 
	"LastName" VARCHAR(255), 
	"Email" VARCHAR(255), 
	"npe01__SystemAccountProcessor__c" VARCHAR(255), 
	"npe01__AlternateEmail__c" VARCHAR(255), 
	"npe01__HomeEmail__c" VARCHAR(255), 
	"npe01__Preferred_Email__c" VARCHAR(255), 
	"npe01__PreferredPhone__c" VARCHAR(255), 
	"npe01__Pråimary_Address_Type__c" VARCHAR(255), 
	"npe01__Private__c" VARCHAR(255), 
	"npe01__Secondary_Address_Type__c" VARCHAR(255), 
	"npe01__WorkEmail__c" VARCHAR(255), 
	"npe01__WorkPhone__c" VARCHAR(255), 
	PRIMARY KEY (id)
);
INSERT INTO "Contact" VALUES(1,'Dalia','Osborn','daliaosborn@example.com','','','daliaosborn@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(2,'Laura','Woodard','laurawoodard@example.com','','','laurawoodard@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(3,'Simon','Davila','simondavila@example.com','','','simondavila@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(4,'Jamarcus','Barnett','jamarcusbarnett@example.com','','','jamarcusbarnett@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(5,'Adrianna','Norman','adriannanorman@example.com','','','adriannanorman@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(6,'Donna','Snow','donnasnow@example.com','','','donnasnow@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(7,'Gary','Wood','garywood@example.com','','','garywood@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(8,'Reagan','Norton','reagannorton@example.com','','','reagannorton@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(9,'Jaylin','Morgan','jaylinmorgan@example.com','','','jaylinmorgan@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(10,'Mira','Decker','miradecker@example.com','','','miradecker@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(11,'Maya','Lambert','mayalambert@example.com','','','mayalambert@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(12,'Finley','Barry','finleybarry@example.com','','','finleybarry@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(13,'Shane','Gibson','shanegibson@example.com','','','shanegibson@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(14,'Ben','Oneill','benoneill@example.com','','','benoneill@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(15,'Maia','Cooley','maiacooley@example.com','','','maiacooley@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(16,'Olive','Leach','oliveleach@example.com','','','oliveleach@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(17,'Oswaldo','Pacheco','oswaldopacheco@example.com','','','oswaldopacheco@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(18,'Nico','Rivers','nicorivers@example.com','','','nicorivers@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(19,'Tiara','Griffith','tiaragriffith@example.com','','','tiaragriffith@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(20,'Declan','Glenn','declanglenn@example.com','','','declanglenn@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(21,'Madalyn','Francis','madalynfrancis@example.com','','','madalynfrancis@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(22,'Mathew','Rhodes','mathewrhodes@example.com','','','mathewrhodes@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(23,'Eli','White','eliwhite@example.com','','','eliwhite@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(24,'Alia','Duarte','aliaduarte@example.com','','','aliaduarte@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(25,'Tatiana','Lang','tatianalang@example.com','','','tatianalang@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(26,'Gia','Ramirez','giaramirez@example.com','','','giaramirez@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(27,'Alejandro','Serrano','alejandroserrano@example.com','','','alejandroserrano@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(28,'Mya','Galloway','myagalloway@example.com','','','myagalloway@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(29,'Adam','Clark','adamclark@example.com','','','adamclark@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(30,'Marisol','Gonzales','marisolgonzales@example.com','','','marisolgonzales@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(31,'Mya','Cobb','myacobb@example.com','','','myacobb@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(32,'Jay','Shah','jayshah@example.com','','','jayshah@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(33,'Nancy','Arroyo','nancyarroyo@example.com','','','nancyarroyo@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(34,'Aubrie','Booker','aubriebooker@example.com','','','aubriebooker@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(35,'Neil','Huerta','neilhuerta@example.com','','','neilhuerta@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(36,'Emelia','Mercer','emeliamercer@example.com','','','emeliamercer@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(37,'Yadiel','Horton','yadielhorton@example.com','','','yadielhorton@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(38,'Taniyah','Rios','taniyahrios@example.com','','','taniyahrios@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(39,'Peyton','Craig','peytoncraig@example.com','','','peytoncraig@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(40,'Francesca','Oliver','francescaoliver@example.com','','','francescaoliver@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(41,'Albert','Montgomery','albertmontgomery@example.com','','','albertmontgomery@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(42,'Meredith','Cooke','meredithcooke@example.com','','','meredithcooke@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(43,'Mckayla','Morrison','mckaylamorrison@example.com','','','mckaylamorrison@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(44,'Hayley','Bright','hayleybright@example.com','','','hayleybright@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(45,'Dayana','Atkins','dayanaatkins@example.com','','','dayanaatkins@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(46,'Laura','Hernandez','laurahernandez@example.com','','','laurahernandez@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(47,'Jessica','Woods','jessicawoods@example.com','','','jessicawoods@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(48,'Khloe','Stanley','khloestanley@example.com','','','khloestanley@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(49,'Ray','Fischer','rayfischer@example.com','','','rayfischer@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(50,'Casey','Kline','caseykline@example.com','','','caseykline@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(51,'Aron','Joyce','aronjoyce@example.com','','','aronjoyce@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(52,'Diego','Case','diegocase@example.com','','','diegocase@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(53,'Chelsea','Graves','chelseagraves@example.com','','','chelseagraves@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(54,'Ruth','Wu','ruthwu@example.com','','','ruthwu@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(55,'Isaac','Grant','isaacgrant@example.com','','','isaacgrant@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(56,'Audrina','Rojas','audrinarojas@example.com','','','audrinarojas@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(57,'Makhi','Villegas','makhivillegas@example.com','','','makhivillegas@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(58,'Koen','Chase','koenchase@example.com','','','koenchase@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(59,'Hailie','Holder','hailieholder@example.com','','','hailieholder@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(60,'Caylee','Pollard','cayleepollard@example.com','','','cayleepollard@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(61,'Guillermo','Quinn','guillermoquinn@example.com','','','guillermoquinn@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(62,'Dominik','Wilkinson','dominikwilkinson@example.com','','','dominikwilkinson@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(63,'Simone','Keller','simonekeller@example.com','','','simonekeller@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(64,'Violet','Ellis','violetellis@example.com','','','violetellis@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(65,'Samir','Neal','samirneal@example.com','','','samirneal@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(66,'Mira','Mcconnell','miramcconnell@example.com','','','miramcconnell@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(67,'Aniya','Arellano','aniyaarellano@example.com','','','aniyaarellano@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(68,'Rafael','Velasquez','rafaelvelasquez@example.com','','','rafaelvelasquez@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(69,'Jakayla','Glover','jakaylaglover@example.com','','','jakaylaglover@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(70,'Angelo','Lutz','angelolutz@example.com','','','angelolutz@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(71,'Audrina','Graves','audrinagraves@example.com','','','audrinagraves@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(72,'Turner','Carson','turnercarson@example.com','','','turnercarson@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(73,'Emelia','Fletcher','emeliafletcher@example.com','','','emeliafletcher@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(74,'Mackenzie','Hernandez','mackenziehernandez@example.com','','','mackenziehernandez@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(75,'Ryan','Hardin','ryanhardin@example.com','','','ryanhardin@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(76,'Mira','Olson','miraolson@example.com','','','miraolson@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(77,'Anna','Orr','annaorr@example.com','','','annaorr@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(78,'Tyrone','Pearson','tyronepearson@example.com','','','tyronepearson@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(79,'Joe','Salinas','joesalinas@example.com','','','joesalinas@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(80,'Maleah','Bullock','maleahbullock@example.com','','','maleahbullock@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(81,'Anika','Solomon','anikasolomon@example.com','','','anikasolomon@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(82,'Tom','Higgins','thiggins@example.com','','','thiggins@example.com','Personal','Home','Home','false','','','');
INSERT INTO "Contact" VALUES(83,'Lisa','Higgins','lhiggins@example.com','','','lhiggins@example.com','Personal','Home','Home','false','','','');
INSERT INTO "Contact" VALUES(84,'Jeremy','Adams','jeremyadams@example.com','','','jeremyadams@example.com','Personal','Home','Home','false','','','');
INSERT INTO "Contact" VALUES(85,'Angela','Adams','angelaadams@example.com','','','angelaadams@example.com','Personal','Home','Home','false','','','');
INSERT INTO "Contact" VALUES(86,'Arthur','Baker','','','','','Personal','Home','Home','false','','','');
INSERT INTO "Contact" VALUES(87,'Arlene','Baker','alanbaker@example.com','','','alanbaker@example.com','Personal','Home','Home','false','','','');
INSERT INTO "Contact" VALUES(88,'Robin','Banks','robinbanks@example.com','','','robinbanks@example.com','Personal','Home','Home','false','','','');
INSERT INTO "Contact" VALUES(89,'Darryl','Graham','darrylgraham@example.com','','','darrylgraham@example.com','Personal','Home','Home','false','','','');
INSERT INTO "Contact" VALUES(90,'Lynn','Barnes','lynnbarnes@example.com','','','lynnbarnes@example.com','Personal','Home','Home','false','','','');
INSERT INTO "Contact" VALUES(91,'David','Barnes','davidbarnes@example.com','','','davidbarnes@example.com','Personal','Home','Home','false','','','');
INSERT INTO "Contact" VALUES(92,'Jason','Barnes','jasonbarnes@example.com','','','jasonbarnes@example.com','Personal','Home','Home','false','','','');
INSERT INTO "Contact" VALUES(93,'Anne','Boyd','anneboyd@example.com','','','anneboyd@example.com','Personal','Home','Home','false','','','');
INSERT INTO "Contact" VALUES(94,'Norma','Burke','normaburke@example.com','','','normaburke@example.com','Personal','Home','Home','false','','','');
INSERT INTO "Contact" VALUES(95,'Ariella','Branch','ariellabranch@example.com','','','ariellabranch@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(96,'Bobby','Henderson','bobbyhenderson@example.com','','','bobbyhenderson@example.com','Personal','Home','Home','false','','','');
INSERT INTO "Contact" VALUES(97,'Anthony','Hill','anthonyhill@example.com','','','anthonyhill@example.com','Personal','Home','Home','false','','','');
INSERT INTO "Contact" VALUES(98,'Virginia','Holmes','virginiaholmes@example.com','','','virginiaholmes@example.com','Personal','Home','Home','false','','','');
INSERT INTO "Contact" VALUES(99,'Jose','Jenkins','josejenkins@example.com','','','josejenkins@example.com','Personal','Home','Home','false','','','');
INSERT INTO "Contact" VALUES(100,'Craig','Johnson','craigjohnso@example.com','','','craigjohnso@example.com','Personal','Home','Home','false','','','');
INSERT INTO "Contact" VALUES(101,'Maya','Johnson','','','','','Personal','Home','Home','false','','','');
INSERT INTO "Contact" VALUES(102,'Barbara','Johnson','barbarajohnson@example.com','','','barbarajohnson@example.com','Personal','Home','Home','false','','','');
INSERT INTO "Contact" VALUES(103,'Jose','Burgess','joseburgess@example.com','','','joseburgess@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(104,'Brenda','Bass','brendabass@example.com','','','brendabass@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(105,'Nikhil','Bishop','nikhilbishop@example.com','','','nikhilbishop@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(106,'Juliette','Cisneros','juliettecisneros@example.com','','','juliettecisneros@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(107,'Alana','Owen','alanaowen@example.com','','','alanaowen@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(108,'Jaydon','Bates','jaydonbates@example.com','','','jaydonbates@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(109,'Cruz','Kerr','cruzkerr@example.com','','','cruzkerr@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(110,'Naima','Crawford','naimacrawford@example.com','','','naimacrawford@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(111,'Beau','Eaton','beaueaton@example.com','','','beaueaton@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(112,'Chance','Rasmussen','chancerasmussen@example.com','','','chancerasmussen@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(113,'Khloe','Campos','khloecampos@example.com','','','khloecampos@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(114,'Amelie','Bond','ameliebond@example.com','','','ameliebond@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(115,'Julie','Myers','juliemyers@example.com','','','juliemyers@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(116,'Jayda','Stanton','jaydastanton@example.com','','','jaydastanton@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(117,'Heidi','Woods','heidiwoods@example.com','','','heidiwoods@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(118,'Leia','Spence','leiaspence@example.com','','','leiaspence@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(119,'Javon','Rodgers','javonrodgers@example.com','','','javonrodgers@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(120,'Leon','Clayton','leonclayton@example.com','','','leonclayton@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(121,'Marc','Richard','marcrichard@example.com','','','marcrichard@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(122,'Jordan','Waller','jordanwaller@example.com','','','jordanwaller@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(123,'Jace','Hampton','jacehampton@example.com','','','jacehampton@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(124,'Silas','Neal','silasneal@example.com','','','silasneal@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(125,'Sonia','Gentry','soniagentry@example.com','','','soniagentry@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(126,'Alison','Barr','alisonbarr@example.com','','','alisonbarr@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(127,'Vu','Pham','vupham@example.com','','','vupham@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(128,'Kellen','Cooley','kellencooley@example.com','','','kellencooley@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(129,'Jay','Zimmerman','jayzimmerman@example.com','','','jayzimmerman@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(130,'Josie','Mcclure','josiemcclure@example.com','','','josiemcclure@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(131,'Melanie','Wheeler','melaniewheeler@example.com','','','melaniewheeler@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(132,'Fernando','Beltran','fernandobeltran@example.com','','','fernandobeltran@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(133,'Yuliana','Bird','yulianabird@example.com','','','yulianabird@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(134,'Alyson','Duffy','alysonduffy@example.com','','','alysonduffy@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(135,'Nyla','Woods','nylawoods@example.com','','','nylawoods@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(136,'James','Richards','jamesrichards@example.com','','','jamesrichards@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(137,'Aaron','Valdez','aaronvaldez@example.com','','','aaronvaldez@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(138,'John','Mills','johnmills@example.com','','','johnmills@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(139,'Shannon','Greene','shannongreene@example.com','','','shannongreene@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(140,'Marco','Escobar','marcoescobar@example.com','','','marcoescobar@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(141,'Marcus','Huynh','marcushuynh@example.com','','','marcushuynh@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(142,'Lorelai','Gross','lorelaigross@example.com','','','lorelaigross@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(143,'Elsa','Guerrero','elsaguerrero@example.com','','','elsaguerrero@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(144,'Yesenia','Ritter','yeseniaritter@example.com','','','yeseniaritter@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(145,'Abraham','Sims','abrahamsims@example.com','','','abrahamsims@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(146,'Kyle','Huffman','kylehuffman@example.com','','','kylehuffman@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(147,'Cora','Hall','corahall@example.com','','','corahall@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(148,'Isaac','Barker','isaacbarker@example.com','','','isaacbarker@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(149,'Kailey','Glass','kaileyglass@example.com','','','kaileyglass@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(150,'Delilah','Ibarra','delilahibarra@example.com','','','delilahibarra@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(151,'Zackery','Morgan','zackerymorgan@example.com','','','zackerymorgan@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(152,'Ayanna','Gonzalez','ayannagonzalez@example.com','','','ayannagonzalez@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(153,'Duncan','Bowers','duncanbowers@example.com','','','duncanbowers@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(154,'Lauryn','Odom','laurynodom@example.com','','','laurynodom@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(155,'Yusef','Flores','yusefflores@example.com','','','yusefflores@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(156,'Semaj','Wall','semajwall@example.com','','','semajwall@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(157,'Frankie','Waller','frankiewaller@example.com','','','frankiewaller@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(158,'Eliezer','Bray','eliezerbray@example.com','','','eliezerbray@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(159,'Jaden','Conner','jadenconner@example.com','','','jadenconner@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(160,'Steven','Harper','stevenharper@example.com','','','stevenharper@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(161,'Karissa','Aguilar','karissaaguilar@example.com','','','karissaaguilar@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(162,'Tiara','Cummings','tiaracummings@example.com','','','tiaracummings@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(163,'Taniya','Singleton','taniyasingleton@example.com','','','taniyasingleton@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(164,'Cecilia','Cardenas','ceciliacardenas@example.com','','','ceciliacardenas@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(165,'Christina','Webster','christinawebster@example.com','','','christinawebster@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(166,'Emilie','Costa','emiliecosta@example.com','','','emiliecosta@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(167,'Ayana','Humphrey','ayanahumphrey@example.com','','','ayanahumphrey@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(168,'Lucia','Cain','luciacain@example.com','','','luciacain@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(169,'Amaya','Dunlap','amayadunlap@example.com','','','amayadunlap@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(170,'Derrick','Blackwell','derrickblackwell@example.com','','','derrickblackwell@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(171,'Alice','Irwin','aliceirwin@example.com','','','aliceirwin@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(172,'Fabian','Hughes','fabianhughes@example.com','','','fabianhughes@example.com','Personal','Home','','false','','','');
INSERT INTO "Contact" VALUES(173,'Raelynn','Wells','raelynnwells@example.com','','','raelynnwells@example.com','Personal','Home','','false','','','');
CREATE TABLE "Opportunity" (
	id INTEGER NOT NULL, 
	"Name" VARCHAR(255), 
	"npe01__Membership_Origin__c" VARCHAR(255), 
	"npe01__Member_Level__c" VARCHAR(255), 
	"npe01__Membership_Start_Date__c" VARCHAR(255), 
	"npe01__Membership_End_Date__c" VARCHAR(255), 
	"npe01__Do_Not_Automatically_Create_Payment__c" VARCHAR(255), 
	PRIMARY KEY (id)
);
INSERT INTO "Opportunity" VALUES(1,'Arthur Baker Donation in Memoriam','','','','','false');
INSERT INTO "Opportunity" VALUES(2,'Darryl Graham 2019 In-Kind Donation','','','','','false');
INSERT INTO "Opportunity" VALUES(3,'Lynn Barnes 1019 Donation','','','','','false');
COMMIT;
